param(
    [string]$RepoRoot = "",
    [switch]$NoDownload
)

$ErrorActionPreference = "Stop"

$SdkVersion = "33.0"
$ReleaseTag = "wasi-sdk-33"
$AssetName = "wasi-sdk-33.0-x86_64-windows.tar.gz"
$AssetUrl = "https://github.com/WebAssembly/wasi-sdk/releases/download/$ReleaseTag/$AssetName"
$AssetSha256 = "df14ca2a2127c2d6b6be07e6f5549b3af9c1b3c0112430c200a4749970c59f06"

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
} else {
    $RepoRoot = (Resolve-Path $RepoRoot).Path
}

function Join-RepoPath([string]$Path) {
    return (Join-Path $RepoRoot $Path)
}

function ConvertTo-TomlPath([string]$Path) {
    return $Path.Replace("\", "\\")
}

function Test-WasiSdkRoot([string]$Path) {
    if ([string]::IsNullOrWhiteSpace($Path) -or !(Test-Path -LiteralPath $Path -PathType Container)) {
        return $false
    }

    $required = @(
        "bin\wasm32-wasip1-clang.exe",
        "share\wasi-sysroot\lib\wasm32-wasip1\libc.a",
        "share\wasi-sysroot\lib\wasm32-wasip1\crt1-command.o",
        "share\wasi-sysroot\lib\wasm32-wasip1\crt1-reactor.o"
    )

    foreach ($relative in $required) {
        if (!(Test-Path -LiteralPath (Join-Path $Path $relative) -PathType Leaf)) {
            return $false
        }
    }

    return $true
}

function Get-ChildSdkCandidates([string]$Root) {
    if (!(Test-Path -LiteralPath $Root -PathType Container)) {
        return @()
    }

    return @(Get-ChildItem -LiteralPath $Root -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like "wasi-sdk*" } |
        ForEach-Object { $_.FullName })
}

function Find-WasiSdkRoot {
    $candidates = New-Object System.Collections.Generic.List[string]

    if (![string]::IsNullOrWhiteSpace($env:WASI_SDK_PATH)) {
        $candidates.Add($env:WASI_SDK_PATH)
    }

    $candidates.Add((Join-RepoPath ".rouwdi\tools\wasi-sdk\wasi-sdk-$SdkVersion-x86_64-windows"))
    $candidates.Add("C:\wasi-sdk")
    $candidates.Add("C:\wasi-sdk-$SdkVersion")
    $candidates.Add("C:\tools\wasi-sdk")
    $candidates.Add("C:\opt\wasi-sdk")

    foreach ($root in @("C:\", "C:\tools", "C:\opt", "C:\Program Files", "C:\Program Files (x86)")) {
        foreach ($candidate in Get-ChildSdkCandidates $root) {
            $candidates.Add($candidate)
        }
    }

    foreach ($candidate in $candidates) {
        if (Test-WasiSdkRoot $candidate) {
            return (Resolve-Path -LiteralPath $candidate).Path
        }
    }

    return $null
}

function Ensure-DownloadedSdk {
    if ($NoDownload) {
        throw "No local WASI SDK was found and -NoDownload was supplied."
    }

    $cacheDir = Join-RepoPath ".rouwdi\tool-cache\wasi-sdk"
    $toolsDir = Join-RepoPath ".rouwdi\tools\wasi-sdk"
    $archivePath = Join-Path $cacheDir $AssetName
    $sdkRoot = Join-Path $toolsDir "wasi-sdk-$SdkVersion-x86_64-windows"

    New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null
    New-Item -ItemType Directory -Force -Path $toolsDir | Out-Null

    if (!(Test-Path -LiteralPath $archivePath -PathType Leaf)) {
        & curl.exe -L --fail --retry 3 --output $archivePath $AssetUrl
        if ($LASTEXITCODE -ne 0) {
            throw "curl failed while downloading $AssetUrl with exit code $LASTEXITCODE"
        }
    }

    $actualSha = (Get-FileHash -Algorithm SHA256 -LiteralPath $archivePath).Hash.ToLowerInvariant()
    if ($actualSha -ne $AssetSha256) {
        throw "WASI SDK archive hash mismatch: expected $AssetSha256, got $actualSha"
    }

    if (!(Test-WasiSdkRoot $sdkRoot)) {
        & tar -xzf $archivePath -C $toolsDir
        if ($LASTEXITCODE -ne 0) {
            throw "tar failed while extracting $archivePath with exit code $LASTEXITCODE"
        }
    }

    if (!(Test-WasiSdkRoot $sdkRoot)) {
        throw "Downloaded WASI SDK did not contain the required wasm32-wasip1 sysroot at $sdkRoot"
    }

    return (Resolve-Path -LiteralPath $sdkRoot).Path
}

function Set-RustBootstrapWasiRoot([string]$WasiRoot) {
    $bootstrapPath = Join-RepoPath "third_party\rust\bootstrap.toml"
    $sectionHeader = "[target.wasm32-wasip1]"
    $setting = "wasi-root = `"$(ConvertTo-TomlPath $WasiRoot)`""

    if (!(Test-Path -LiteralPath $bootstrapPath -PathType Leaf)) {
        $content = @(
            "# Generated by bootstrap/provision-wasi-sdk.ps1.",
            "# This file is ignored by third_party/rust/.gitignore.",
            "",
            $sectionHeader,
            $setting,
            ""
        )
        Set-Content -LiteralPath $bootstrapPath -Value $content -Encoding UTF8
        return
    }

    $lines = @(Get-Content -LiteralPath $bootstrapPath)
    $sectionStart = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq $sectionHeader) {
            $sectionStart = $i
            break
        }
    }

    if ($sectionStart -lt 0) {
        $lines += ""
        $lines += $sectionHeader
        $lines += $setting
        Set-Content -LiteralPath $bootstrapPath -Value $lines -Encoding UTF8
        return
    }

    $sectionEnd = $lines.Count
    for ($i = $sectionStart + 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match "^\s*\[.+\]\s*$") {
            $sectionEnd = $i
            break
        }
    }

    $settingIndex = -1
    for ($i = $sectionStart + 1; $i -lt $sectionEnd; $i++) {
        if ($lines[$i] -match "^\s*wasi-root\s*=") {
            $settingIndex = $i
            break
        }
    }

    if ($settingIndex -ge 0) {
        $lines[$settingIndex] = $setting
    } else {
        $before = @()
        if ($sectionStart -ge 0) {
            $before = $lines[0..$sectionStart]
        }
        $after = @()
        if ($sectionStart + 1 -lt $lines.Count) {
            $after = $lines[($sectionStart + 1)..($lines.Count - 1)]
        }
        $lines = @($before + $setting + $after)
    }

    Set-Content -LiteralPath $bootstrapPath -Value $lines -Encoding UTF8
}

$sdkRoot = Find-WasiSdkRoot
$source = "detected"
if ($null -eq $sdkRoot) {
    $sdkRoot = Ensure-DownloadedSdk
    $source = "downloaded"
}

$wasiRoot = Join-Path $sdkRoot "share\wasi-sysroot"
$targetLibdir = Join-Path $wasiRoot "lib\wasm32-wasip1"
Set-RustBootstrapWasiRoot $wasiRoot

$env:WASI_SDK_PATH = $sdkRoot

[pscustomobject]@{
    status = "ready"
    source = $source
    wasi_sdk_root = $sdkRoot
    wasi_root = $wasiRoot
    target_libdir = $targetLibdir
    rust_bootstrap_config = (Join-RepoPath "third_party\rust\bootstrap.toml")
    environment_assignment = "`$env:WASI_SDK_PATH = `"$sdkRoot`""
    target_pack_command = "cd third_party/rust; python x.py build library/std --stage 1 --target wasm32-wasip1 -v"
} | ConvertTo-Json -Depth 3
