#ifndef ROUWDI_WASI_SDK_SHIM_MACHINE_ENDIAN_H
#define ROUWDI_WASI_SDK_SHIM_MACHINE_ENDIAN_H

#define LITTLE_ENDIAN 1234
#define BIG_ENDIAN 4321
#define PDP_ENDIAN 3412
#define BYTE_ORDER LITTLE_ENDIAN

#define _LITTLE_ENDIAN LITTLE_ENDIAN
#define _BIG_ENDIAN BIG_ENDIAN
#define _PDP_ENDIAN PDP_ENDIAN
#define _BYTE_ORDER BYTE_ORDER

#endif
